version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: dostlik_postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dostlik_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: dostlik_django_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=dostlik_db
      - DB_USER=postgres
      - DB_PASSWORD=1111
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-test-key

volumes:
  postgres_data:
#
#
#
#
#







  #
  # rabbitmq:
  #   image: rabbitmq:management
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #
  #
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #
  # celery:
  #   build: .
  #   command: celery -A config worker --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - rabbitmq
  #     - redis
  #   env_file:
  #     - ./.env