# Generated by Django 6.0.6 on 2026-07-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Menyular',
            },
        ),
    ]
