# Generated by Django 6.0.6 on 2026-07-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_picture_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
