# Generated by Django 6.0.6 on 2026-07-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='picture',
            new_name='image',
        ),
    ]
